### PR TITLE
:factory: Add BasicAuth addon

### LINKED ISSUE #221: Basic auth middleware/extension
Would you be interested in a basic auth middleware/extension? Currently, if a URL contains basic auth credentials `fetch` and by extension `wretch` will just throw an error.

The middleware I'd like to implement would extract the username/pw from the URL and add them as an `Authorization` header.  
The extension could provide a `basicAuth` method so that users don't have know how to construct a basic auth header themselves.

### PR DESCRIPTION
**Pull request by BendingBender**
Implement BasicAuth addon that adds following behaviors:
- allows setting credentials via the `.basicAuth()` method
- parses URLs and extracts credentials from them, converting them to an `Authorization` header and removing them from the URL which would otherwise throw an error when passed to native `fetch()`
- correctly encodes usernames/passwords that contain non-latin characters (see https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem)

Fixes #221

### CODE REVIEW

**Comment by BendingBender** [comment]
I have a question here: I also use the `encodeURIComponent` and `btoa` globals in my addon. Should I inject them via the `polyfill` system, just like `URL` and `TextEncoder` or do you think that this is the absolute baseline that doesn't need polyfilling?

**Comment by ChiliBoyRed** [comment]
> I have a question here: I also use the `encodeURIComponent` and `btoa` globals in my addon. Should I inject them via the `polyfill` system, just like `URL` and `TextEncoder` or do you think that this is the absolute baseline that doesn't need polyfilling?

If you intend to make this compatible with React Native, it doesn't support atob or btoa (yet) other than through polyfills.

**Comment by BendingBender** [comment]
> > I have a question here: I also use the `encodeURIComponent` and `btoa` globals in my addon. Should I inject them via the `polyfill` system, just like `URL` and `TextEncoder` or do you think that this is the absolute baseline that doesn't need polyfilling?
> 
> If you intend to make this compatible with React Native, it doesn't support atob or btoa (yet) other than through polyfills.

This should already work in any environment that has native `btoa` or has it already polyfilled globally. So the question is actually whether we need to support local polyfills (i.e. only for this lib). I don't use RN and have no experience with it. Can you tell me whether it's common to globally polyfill `btoa` there?

**Review by elbywan — APPROVED** [review]
👏 👍 Excellent work, thanks a bunch for this PR! And really sorry for not reviewing earlier (I have been quite busy these last 2 months).

I just have a couple of comments regarding polyfills:
- polyfilling `URL` / `TextEncoder` is not strictly necessary since the minimum level of support we are aiming for is node 14 which includes both out of the box
- I'm fine with not polyfilling `btoa` / `atob`, regarding react native it seems like they are already supporting it (or will be very soon): https://github.com/facebook/hermes/issues/1178

**Comment by BendingBender** [comment]
Just a small note: I use `URL.canParse()` which is supported since node 18.17 (according to MDN). This means that strictly speaking, polyfilling URL will be necessary on node 14. Should I stop using the polyfill system for the `TextEncoder`?

**Comment by elbywan** [comment]
> I use URL.canParse() which is supported since node 18.17 (according to MDN).

Oh sorry I did not get that 👍.

> Should I stop using the polyfill system for the TextEncoder?

Yes I think using the global `TextEncoder` would be fine.

**Comment by BendingBender** [comment]
Done

**Pull request merged**
