### PR TITLE
Test on multiple versions of node and clarify node support policy

### PR DESCRIPTION
**Pull request by Holi0317**
- [ ] 😛 Didn't (Can't) test the CI run until opening this PR. Please don't merge until the CI pass
- [x] 🧐 I think (but am not sure) browser test will emit coverage. So I've removed that part in browser CI
- [x] 🤔 Changing the supported node version is kinda breaking change? Should I use 🔥 emoji in commit log instead?

I am planning on writing tests that use native fetch from node >= 18. But want to land this CI change first to make sure my change won't break running test on earlier versions of node.

### CODE REVIEW

**Comment by Holi0317** [comment]
@elbywan Mind approve the workflow run? Thanks.

**Comment by Holi0317** [comment]
:eyes: The test breaks on node 18 because `restify` does not support it. (https://github.com/restify/node-restify/issues/1888).

@elbywan Would you mind if I migrate the mock server to use [fastify] instead?

[fastify]: https://github.com/fastify/fastify

**Comment by elbywan** [comment]
Hey @Holi0317!

> I think (but am not sure) browser test will emit coverage. So I've removed that part in browser CI

Yes this is fine to split the github workflow. I'm pretty sure only the node.js tests emit coverage.

> Changing the supported node version is kinda breaking change? Should I use 🔥 emoji in commit log instead?

Yes please, 🔥 is the way to go. You can make an atomic commit with only `engine >= 14` if you want the rest to fall under ✅ .

> Would you mind if I migrate the mock server to use [fastify](https://github.com/fastify/fastify) instead?

Not at all, Restify is not really futureproof as you noted 😉. Having fastify would be way better.

---- 

Thanks a bunch this is a **great** contribution 👏!

I am 100% up for setting up matrix testing for node & experimental fetch, and ideally I would even add deno to the mix!

On a side note, by coincidence I'm currently working on a `v2` branch which is a big refactoring of the code that will get released soon.

Would you mind working from there and rebasing your PR there instead of main? I did not touch the CI part so I guess there will not be that many conflicts (unless you started changing the specs already). 🙏

**Comment by Holi0317** [comment]
Migration to fastify took a bit more time than expected. I need more time on it.

---

> On a side note, by coincidence I'm currently working on a v2 branch which is a big refactoring of the code that will get released soon.
>
> Would you mind working from there and rebasing your PR there instead of main? I did not touch the CI part so I guess there will not be that many conflicts (unless you started changing the specs already). 🙏

Sure. I only changed CI part and the mock serer. I will first

1. Fix fastify so that all test are green base on current master
2. Rebase to `dev`
3. Test again and see if my mock server break anything

Somehow the specs are testing both wretch and the mock server. And fastify implement things a bit differently compare to restify.

**Comment by Holi0317** [comment]
Status update:

1. Rebased the commits
2. Reaplce mock server with fastify should be completed
3. In node 14, the test "should program resolvers" fails, even with old restify mock server
  - :eyes: BTW you may want to look into https://jestjs.io/docs/expect#expectassertionsnumber
4. Node 16 all test are green
5. Node 18 test breaks. I will look into it
6. Browser test should pass now

**Comment by Holi0317** [comment]
Just fixed node 18 test. Can I leave the "should program resolvers" fix to you @elbywan?

**Comment by elbywan** [comment]
> Just fixed node 18 test. Can I leave the "should program resolvers" fix to you @elbywan 👀?

Sure, I'll have a look when I have some free time! 👍

**Comment by elbywan** [comment]
@Holi0317 Allright, specs should be good now: https://github.com/elbywan/wretch/commit/ca8b559eb9821901a6d9d8deb5bfebee56225a09

**Comment by Holi0317** [comment]
Should be ready to merge 🎉.

**Comment by elbywan** [comment]
Excellent work, thanks a bunch! 🙇 👍

**Pull request merged**
